Load original image if image optimize is not done yet
statikbe/craft pull request #414
Opened 2024-12-09 14:20 UTC by KarelJanVanHaute

Fixes #411

### Description

### Reason for this change

2024-12-09 15:06 UTC, emilyberghen requested changes

2024-12-09 15:06 UTC, emilyberghen commented on templates/_site/_snippet/_item/_card.twig
> +                            <img src="{{ optimizedImage.optimizedImageUrls|length == 0 ? image.getUrl() : optimizedImage.placeholderBox() }}"
Ik krijg hier een error op de image.getUrl(), denk dat je de overviewImage variabele moet pakken.

2024-12-09 15:22 UTC, KarelJanVanHaute commented on templates/_site/_snippet/_item/_card.twig
> +                            <img src="{{ optimizedImage.optimizedImageUrls|length == 0 ? image.getUrl() : optimizedImage.placeholderBox() }}"
Juist. Aangepast

2024-12-09 15:25 UTC, emilyberghen approved these changes

2025-02-12 12:44 UTC, HannahDeWachter commented
@KarelJanVanHaute wil jij merge conflict oplossen?

2025-02-12 14:39 UTC, merged